### ISSUE TITLE
모달창 UI & API 연결

### ISSUE THREAD

**Issue by postop09** [postop09/Gamsung#3]
# 모달창 UI & API 연결
## UI 개선
- [x] 이미지 클릭 시, 해당 게시물 상세보기 페이지로 이동
- [x] 게시글 상세보기 페이지에서 이미지 클릭 이벤트
- [x]  로그아웃 기능
- [x] 로그아웃/상품/게시글 별 삭제 모달창 UI
- [x] 나의 게시글/댓글과 유저들의 게시글/댓글을 구분하는 모달창 출력

## API 연결
- [x] 홈 페이지 게시글 신고 API
- [x] 로그아웃/상품/게시글 별 삭제 API
- [x] 내 프로필 페이지 삭제 API
- [x] 상품 웹페이지로 이동 API
- [x] 나의 게시글/댓글과 유저들의 게시글/댓글을 구분하는 API

**Comment by kimq1005** [comment]
너무 너무 좋은 커밋이네요 ~*^_^**

**Comment by postop09** [comment]
# 상품 웹 페이지로 이동 오류

- 페이지 출력 'Cannot GET /Gamsung/src/pages/www.naver.com'
- 콘솔 출력 'Failed to load resource: the server responded with a status of 404 (Not Found)'
